### PR TITLE
Tables and Last Commit Date

### PR DESCRIPTION
**Pull request by mutewinter**
How do you feel about the table look? Emoji responses!

### CODE REVIEW

**Comment by tinystride** [comment]
I like it! Easier to parse. One suggestion: maybe switch back to left-aligned stars, and place the star to the left of the number. The right-alignment seems a little uncommon.

This is so great! 🎉

**Comment by tinystride** [comment]
I noticed this broken layout on the final table:

screen shot 2016-09-09 at 10 32 37 am

**Comment by mutewinter** [comment]
@tinystride updated, moved stars, and realized that relative dates are silly since this won't update often enough to be accurate.

**Comment by ginatrapani** [comment]
big improvement!

**Comment by spiffytoy** [comment]
This is awesome! Thanks for putting it together. 🙌

**Pull request merged**
