### PR TITLE
Add Awesome Cms Core (I'm the main contributor)

### PR DESCRIPTION
**Pull request by ngohungphuc**
- [x] verified that the CMS I'm adding is still maintained.
- [x] read [CONTRIBUTING.md](https://github.com/postlight/awesome-cms/blob/master/CONTRIBUTING.md).
- [x] did not generate README.md.

### CODE REVIEW

**Comment by ngohungphuc** [comment]
@mutewinter please review

**Comment by mutewinter** [comment]
Thanks @ngohungphuc. You'll need 50 stars before we can add it to the list. See the contributing doc: https://github.com/postlight/awesome-cms/blob/master/CONTRIBUTING.md

**Comment by ngohungphuc** [comment]
Hi @mutewinter please merge this pr. My repo already have 50 star

**Comment by ngohungphuc** [comment]
Hi @mutewinter please merge this pr. My repo already have 50 star

**Pull request closed without merging**
