### PR TITLE
Add Winter CMS

### PR DESCRIPTION
**Pull request by LukeTowers**
- [x] verified that the CMS I'm adding is still maintained.
- [x] read [CONTRIBUTING.md](https://github.com/postlight/awesome-cms/blob/master/CONTRIBUTING.md).
- [x] did not generate README.md.

### CODE REVIEW

**Review by Technetium1 — APPROVED** [review]
This is good.

**Comment by fdsimms** [comment]
thanks for the PR @LukeTowers and for the approval @Technetium1!

**Comment by LukeTowers** [comment]
Thanks for the merge @fdsimms!

**Comment by LukeTowers** [comment]
@fdsimms huh, just looking at this now and for some reason the PR added the file to the root of the project instead of in the data folder. Are you able to fix that or do you need me to make a separate PR to fix that?

**Comment by fdsimms** [comment]
ah i should have noticed that—got in a groove merging these PRs and overlooked it. don't worry about it, i'll fix it

**Comment by LukeTowers** [comment]
No worries, thanks!

**Pull request merged**
