### PR TITLE
add awesome cms core

### PR DESCRIPTION
**Pull request by ngohungphuc**
- [x] verified that the CMS I'm adding is still maintained.
- [x] read [CONTRIBUTING.md](https://github.com/postlight/awesome-cms/blob/master/CONTRIBUTING.md).
- [x] did not generate README.md.

### CODE REVIEW

**Comment by ngohungphuc** [comment]
Hi @mutewinter Please review it again.
Thank you.

**Comment by ngohungphuc** [comment]
Hi @mutewinter Please review it again.
Thank you.

**Comment by ngohungphuc** [comment]
Hi @mutewinter Please review it again. Thank you.

**Comment by ngohungphuc** [comment]
Hi @mutewinter any update on this ?

**Comment by ngohungphuc** [comment]
Hi @mutewinter any update on this ?

**Comment by mutewinter** [comment]
Thank you, @ngohungphuc!

**Pull request merged**
